DECLARE 
    V_TABUADA NUMBER(2):= &tabuada;
    V_CONTADOR NUMBER(2):=0;
BEGIN
LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR || 'X' || V_TABUADA || '=' || V_CONTADOR * V_TABUADA);
    V_CONTADOR := V_CONTADOR + 1;
    EXIT WHEN V_CONTADOR > 10;

END LOOP;
END;